repos:
- hooks:
  - id: check-added-large-files
  - id: check-ast
    exclude: (notebooks*)
  - id: fix-byte-order-marker
  - id: check-docstring-first
  - id: check-json
  - id: pretty-format-json
  - id: check-merge-conflict
  - id: check-toml
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: sort-simple-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
- hooks:
  - id: black
    exclude: (notebooks*)
  repo: https://github.com/psf/black
  rev: 22.6.0
- hooks:
  - args:
    - --in-place
    id: docformatter
  repo: https://github.com/myint/docformatter
  rev: v1.7.5
- hooks:
  - id: detect-secrets
    exclude: (notebooks*)
    name: Detect secrets
    description: Detects high entropy strings that are likely to be passwords.
    entry: detect-secrets-hook
    language: python
    # for backward compatibility
    files: .*
  repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
- hooks:
  - id: mypy
    exclude: 'common/modules.py|notebooks'
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.1
- hooks:
  - id: forbid-binary
  - id: shellcheck
  - id: shfmt
  repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
- hooks:
  - id: dockerfilelint
    stages:
    - commit
  repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
- hooks:
  - args:
    - --exclude
    - tests, notebooks
    - -s
    - B101
    files: .py$
    id: bandit
  repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
- hooks:
  - id: isort
    exclude: (notebooks*)
    name: isort (python)
  repo: https://github.com/pycqa/isort
  rev: 5.12.0
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --in-place]
